#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00

set -xe

input=$(jq -r .bold config.json)
nhood=$(jq -r .neighborhood config.json)

time singularity run -e \
    docker://anibalsolon/app-reho:v0.0.1 \
    -inset $input \
    -prefix reho.nii.gz \
    -nneigh $nhood

mkdir -p reho
mv reho.nii.gz reho/reho.nii.gz
